language: node_js
node_js:
  - "8"
script:
  - npm test
  - npm run contributing-test #remove this line if you're not contributing - https://github.com/topheman/webpack-babel-starter/tree/master/contributing
